# Generated by Django 3.2 on 2021-05-01 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('svg', models.CharField(max_length=2000)),
                ('show_svg', models.CharField(max_length=2000)),
                ('category_id', models.IntegerField()),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('font_class', models.CharField(max_length=10)),
                ('height', models.IntegerField(default=1024)),
                ('width', models.IntegerField(default=1024)),
                ('is_private', models.BooleanField(default=False)),
                ('slug', models.SlugField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='iconLibs',
            fields=[
                ('icon_libs_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('all_count', models.IntegerField(default=0)),
                ('created_user', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slugs', models.SlugField()),
                ('likes_count', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(default='default/avatar_default.png', upload_to='avatar')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=10)),
                ('weixin_code', models.ImageField(default='default/userWeixinCode_default.png', upload_to='userWeixinCode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libs_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.data')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.user')),
            ],
        ),
        migrations.CreateModel(
            name='favorites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.iconlibs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.user')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='libs_belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.iconlibs'),
        ),
    ]
