# Generated by Django 3.2 on 2021-05-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_file',
            field=models.ImageField(blank=True, null=True, upload_to='illustration'),
        ),
        migrations.AddField(
            model_name='data',
            name='data_type',
            field=models.CharField(default='icon', max_length=10),
        ),
        migrations.AddField(
            model_name='data',
            name='origin_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='prototype_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='show_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
