# Generated by Django 3.2 on 2021-05-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0002_auto_20210502_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='data',
            name='prototype_svg',
        ),
    ]
