# Generated by Django 3.2 on 2021-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0003_auto_20210502_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='prototype_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
