# Generated by Django 3.2 on 2021-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0004_data_prototype_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_type',
            field=models.CharField(default='icon', max_length=10),
        ),
    ]
