# Generated by Django 3.2 on 2021-05-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0006_auto_20210502_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(default='icon', max_length=30),
        ),
    ]
