# Generated by Django 3.2 on 2021-05-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0009_auto_20210502_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(default='https://i.postimg.cc/nh33qHZ5/0d6de2b8-s.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='qq',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
