# Generated by Django 3.2 on 2021-05-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0010_auto_20210503_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconlibs',
            name='has_secret',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iconlibs',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
