# Generated by Django 3.2 on 2021-05-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0011_auto_20210504_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconlibs',
            name='created_user',
            field=models.IntegerField(),
        ),
    ]
