# Generated by Django 3.2 on 2021-05-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0012_alter_iconlibs_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconlibs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.data'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='libs_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ICS.iconlibs'),
        ),
    ]
