# Generated by Django 3.2 on 2021-05-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0013_auto_20210504_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
