# Generated by Django 3.2 on 2021-05-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0014_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pay_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weixin_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
