# Generated by Django 3.2 on 2021-05-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICS', '0017_data_path_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='aiTagInfo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
